name: extensions-configuration - publish

on:
  workflow_dispatch:

env:
  SLN_DIR: src/ilandev.Extensions.Configuration
  NUGET_SRC: https://api.nuget.org/v3/index.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
        
    - name: dotnet restore
      run: dotnet restore
      working-directory: ${{ env.SLN_DIR }}
      
    - name: dotnet test
      run: dotnet test --no-restore
      working-directory: ${{ env.SLN_DIR }}
      
    - name: dotnet pack
      run: dotnet pack --no-restore -o ./output
      working-directory: ${{ env.SLN_DIR }}
      
    - name: dotnet push
      run: dotnet nuget push "./output/*.nupkg" -k ${{ secrets.NUGETORG_KEY }} -s ${{ env.NUGET_SRC }}
      working-directory: ${{ env.SLN_DIR }}
